- name: Install node modules
  local_action:
    module: shell npm install
    chdir: ../code/scratch-gui
  register: command_result
  changed_when: False

#- debug: msg="{{ command_result.stdout }}"

- name: Webpack Scratch GUI
  local_action:
    module: shell npm run build
    chdir: ../code/scratch-gui
  register: command_result
  changed_when: False

#- debug: msg="{{ command_result.stdout }}"
