- name: Upload docker to rpi
  synchronize:
    src: ../docker/
    dest: ~/CodePlayerBox/docker-scratch-gui/
    rsync_opts:
      - "--delete"
      - "--exclude=.DS_Store"
      - "--exclude=code"
      - "--exclude=script"
      - "--exclude=node_modules"

- name: Upload scratch-gui to rpi
  synchronize:
    src: ../code/scratch-gui/build/
    dest: ~/CodePlayerBox/docker-scratch-gui/code/scratch-gui
    rsync_opts:
      - "--delete"
      - "--exclude=.DS_Store"
      - "--exclude=node_modules"
      - "--exclude=dist"

- name: Upload script to rpi
  synchronize:
    src: ../script/
    dest: ~/CodePlayerBox/docker-scratch-gui/script
    rsync_opts:
      - "--delete"
      - "--exclude=.DS_Store"

